name: Terraform Plan

on: [push]

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Decrypt large secret
      run: ./.github/scripts/decrypt_secret.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Validate variables
      run: |
        echo $AWS_ACCESS_KEY_ID
        echo $AWS_SECRET_ACCESS_KEY

    - name: Install Terraform
      run: |
        echo Installing terraform
        sudo snap info terraform
        sudo snap install terraform 
    
    - name: Terraform init
      run: terraform init
      
    - name: Terraform validation
      run: terraform validate
    
    - name: Terraform plan
      run: terraform plan



jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: $
      # This command is just an example to show your secret being printed
      # Ensure you remove any print statements of your secrets. GitHub does
      # not hide secrets that use this workaround.
      - name: Test printing your secret (Remove this step in production)
        run: cat $HOME/secrets/my_secret.json
