name: Terraform Plan

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Install Terraform
      run: |
        echo Installing terraform
        sudo snap install terraform
        
    - name: Terraform init
      run: terraform init
      
    - name: Terraform validation
      run: terraform validate
    
    - name: Terraform plan
      run: terraform plan
        
